print("x:")
x = input()
print("*a:")
a = input()
print("/b:")
b = input()
print("+c:")
c = input()
print("-d:")
d = input()
total = float(x) * float(a) / float(b) + float(c) - float(d)
print(x + " * " + a + " / " + b + " + " + c + " - " + d + " = " + str(total))